
export const serverErrorMessages = [
  "Oops, it looks like my home 🏠 is temporarily offline! Don't worry, I'll be back online soon. Please try again in a bit! 🤗",
  "I'm taking a quick coffee break ☕️, but it looks like my server is experiencing some issues. Please try again soon, and I'll be back to chat with you! 😊",
  "Whoops, it seems I've encountered a tiny server glitch 🎮! Don't worry, my team is on it, and I'll be back online soon. Thanks for your patience! 😊",
  "Uh-oh, it looks like my connection to the cloud ⛅️ is experiencing some turbulence! Please bear with me, and I'll try to reconnect soon. Thanks for understanding! 🤗",
  "I'm feeling a bit sleepy 😴, and it looks like my server is too! I'll try to wake up soon and get back to chatting with you. Thanks for waiting! 😊",
  "Whoops, it looks like my server is on a safari adventure 🦁🌳 and got lost along the way! Don't worry, I'll try to track it down and get back online soon. 🐾",
  "Space alert! 🚀 It seems my server has encountered a glitchy galaxy 🌌 and is experiencing some technical difficulties. Please bear with me while I try to navigate through this astro-tastic issue! 💫",
  "Uh-oh, it looks like my server has powered down 🔌 and is taking an unexpected nap! 😴 Don't worry, I'll try to recharge and get back online soon. 💻",
  "Whoa, it seems my server has floated away to a different cloud ☁️ and is having some connection troubles! 🌫️ I'll try to retrieve it and get back to chatting with you soon. ☁️",
  "Whoops, it looks like my server has encountered an internet intersection 🚦 and is experiencing some traffic congestion! 🚗 Don't worry, I'll try to reroute and get back online soon. 🌐",
  "I'm currently in maintenance mode 🔧 and my server is undergoing some quick repairs! 💻 Please try again soon, and I'll be back online in no time. 📆",
  "Uh-oh, it seems my server has set sail on a network navigation 🚣‍♀️ journey and has encountered some rocky waters! 🌊 Don't worry, I'll try to chart a new course and get back online soon. 🗺️",
  "Whoa, it looks like my server has been caught in a server storm ⛈️ and is experiencing some technical difficulties! 💻 Please bear with me while I try to weather the storm and get back online soon. ☁️",
  "I'm taking a quick caffeine break ☕️, but it looks like my server needs a boost too! 😴 Don't worry, I'll try to perk it up and get back online soon. 💻",
  "Uh-oh, it seems my server has encountered some technical troubles! 🧐 Don't worry, I'm on it and will try to troubleshoot and get back online soon. 💻 Thanks for your patience! 🕰️"
];

export const serverConnectedMessages = [
  "Server's Back Online 💻",
  "Connection Reestablished 📈",
  "We're Back Strong 💪",
  "Server Restarted 🔄",
  "Connection Restored 🔗",
  "We're Online Again 🌐",
  "Server Recovery Complete ✅",
  "Connected Again 🤝",
  "All Good Now 👍",
  "Server's Online Now 💻",
  "Reconnected 📢",
  "We're Live Again 📺",
  "Server's Up Again ⚡️",
  "Connected Successfully 🤝",
  "Server's Coffee Break Over ☕️",
  "Power Nap Over 😴",
  "Space Mission Complete 🚀",
  "Turbulent Times Over ⛅️",
  "Maintenance Over 🔧",
  "Caffeine Reboot 💻",
  "Navigation Charts Fixed 🗺️",
  "Galaxy Reconnected 🌌",
  "Internet Highway Reopened 🚗"
];

export const createNewChatMessages = [
  "Your chatbox is looking a bit empty! 🌱 You can fill it by simply hitting that 'Create New Chat' button!",
  "Let’s spark some joy! ✨ Just click the 'Create New Chat' button to start your journey!",
  "Ready to make some memories? 🌈 Create a new chat by clicking that shiny button!",
  "Don’t be shy! 🎉 Hit 'Create New Chat' to kick off a fun conversation!",
  "Looks like there’s a blank canvas here! 🖌️ Get started by clicking 'Create New Chat'!",
  "Your chat adventure awaits! 🚀 Just click 'Create New Chat' to begin!",
  "Feeling social? 🌟 Hit that 'Create New Chat' button to connect with someone new!",
  "Let’s get chatting! 💬 Click the 'Create New Chat' button to dive in!",
  "The fun starts here! 🌟 Create a new chat by simply clicking that button!",
  "Your next conversation is just a click away! 👉 Hit 'Create New Chat' to get started!",
  "Ready to share your thoughts? 🗣️ Just click 'Create New Chat' and let’s go!",
  "It’s time for some fun! 🎈 Click 'Create New Chat' to begin your chat journey!",
  "Want to meet someone new? 🤝 Create a new chat by hitting that button!",
  "Let’s make this space lively! 🎊 Just click 'Create New Chat' to start!",
  "Exciting conversations await! 🎉 Simply hit the 'Create New Chat' button to begin!"
];

export const startConversationMessages = [
  "It’s quiet here! 🌼 Say hello to start a new conversation!",
  "Ready to chat? 😊 You can start by typing 'Hey' or 'Hello'!",
  "Let’s break the ice! ❄️ Just say 'Hi' to kick off a conversation!",
  "Don’t be shy! 👋 Type 'Hey' or 'What’s up?' to start chatting!",
  "Your voice matters! 🎤 Start by saying 'Hello' or anything you like!",
  "Looking to connect? 🌟 Just type 'Hi' to begin a new conversation!",
  "The chat is waiting for you! 💬 Start by saying 'Hey there'!",
  "Want to share something? 🤗 Type 'Hello' to get started!",
  "Let’s get the chat going! 🎉 Just say 'Hi' or anything you want!",
  "Time to chat! 🗨️ Start by typing 'Hello' or 'How’s it going?'",
  "It’s a great day to connect! 🌞 Just say 'Hi' to start chatting!",
  "Let’s start a conversation! 🚀 Type 'Hey' or ask anything!",
  "Your thoughts matter! 🌼 Start by saying 'Hello' or 'What’s on your mind?'",
  "Feeling curious? 🤔 Just say 'Hi' to kick off the conversation!",
  "Let’s have a chat! 🎈 Type 'Hey there' or 'What’s up?' to begin!"
];

export const months = [
    'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December'
  ];

export const genders = ["Male", "Female" , "Rather Not Say"]

export const educations = ["Kinder Garden", "Primary School", "Secondary School", "High School", "Diploma", "Graduate", "Post Graduate", "Doctorate"]

export const gradientClasses = [
  'from-blue-500 to-indigo-500',
  'from-green-500 to-teal-500',
  'from-purple-600 to-pink-600',
  'from-yellow-500 to-orange-500',
  'from-red-500 to-yellow-500',
  'from-blue-800 to-blue-600',
  'from-teal-600 to-green-600',
  'from-indigo-600 to-purple-600',
  'from-pink-500 to-red-500',
  'from-fuchsia-500 to-purple-500',
  'from-cyan-500 to-blue-500',
  'from-lime-500 to-green-500',
  'from-amber-500 to-yellow-500',
  'from-rose-500 to-pink-500',
  'from-emerald-500 to-teal-500',
  'from-sky-500 to-blue-500',
  'from-violet-500 to-purple-500',
  'from-orange-500 to-red-500',
  'from-yellow-600 to-orange-600'
];

export const interestsArray = [
  "Pokemon",
  "Dinosaurs",
  "Toy cars",
  "Lego building",
  "Superheroes",
  "Harry Potter",
  "Minecraft",
  "Nerf guns",
  "Action figures",
  "Roblox",
  "Disney princesses",
  "Sonic the Hedgehog",
  "Transformers",
  "Spiderman",
  "Avengers",
  "Mario games",
  "Animal crossing",
  "Barbie dolls",
  "Paw Patrol",
  "SpongeBob",
  "Power Rangers",
  "Sharks",
  "Unicorns",
  "Star Wars",
  "Frozen",
  "Cars (movie)",
  "Jurassic World",
  "Ninjago",
  "Scooby-Doo",
  "Minions",
  "Looney Tunes",
  "Tom and Jerry",
  "Beyblade",
  "Slime",
  "Hot Wheels",
  "Baking cookies",
  "Drawing",
  "Super Mario",
  "Cuphead",
  "TikTok dances",
  "Football",
  "Basketball",
  "Bicycling",
  "Skateboarding",
  "Puzzles",
  "Dinosaur skeletons",
  "Stuffed animals",
  "Art and crafts",
  "Trolls (movie)",
  "Zootopia",
  "Toy Story",
  "Shrek",
  "Super Smash Bros",
  "My Little Pony",
  "Racing games",
  "Scooters",
  "Board games",
  "Sloths",
  "Zombies",
  "Creepers (Minecraft)",
  "Among Us",
  "Hatchimals",
  "Octonauts",
  "Sea animals",
  "Drawing superheroes",
  "Origami",
  "Fortnite dances",
  "Jurassic Park",
  "Astrology",
  "Space exploration",
  "Spacex",
  "Astronauts",
  "Magnet building sets",
  "Pikachu",
  "Mewtwo",
  "Charizard",
  "T-Rex",
  "Triceratops",
  "Stegosaurus",
  "Plants vs Zombies",
  "Dora the Explorer",
  "Bluey",
  "The Loud House",
  "Bubble Guppies",
  "Kung Fu Panda",
  "Big Hero 6",
  "Wall-E",
  "Lilo and Stitch",
  "Despicable Me",
  "Angry Birds",
  "Star Wars Lego",
  "Robots",
  "Spaceships",
  "Aliens",
  "Time travel",
  "Magic tricks",
  "DC superheroes",
  "Batman",
  "Wonder Woman",
  "Aquaman",
  "The Flash",
  "Pikmin",
  "Yoshi",
  "Kirby",
  "Adventure Time",
  "Gumball",
  "Teen Titans",
  "Ben 10",
  "Overwatch",
  "Plants",
  "Gardening",
  "Weather patterns",
  "Storms",
  "Volcanoes",
  "Ninja Turtles",
  "How to Train Your Dragon",
  "Spy Kids",
  "Home Alone",
  "LEGO Ninjago",
  "LEGO City",
  "Stop-motion animation",
  "Football trading cards",
  "Pokemon cards",
  "Yu-Gi-Oh cards",
  "Bakugan",
  "Drawing anime characters",
  "Fantasy worlds",
  "Harry Potter spells",
  "Magic wands",
  "Fairy tales",
  "Mythical creatures",
  "Dragons",
  "Trolls",
  "Fairies",
  "Wizards",
  "Tinkerbell",
  "Bugs",
  "Insects",
  "Bees",
  "Butterflies",
  "Ant colonies",
  "Ladybugs",
  "Space rockets",
  "Helicopters",
  "Airplanes",
  "Submarines",
  "Coral reefs",
  "Sea turtles",
  "Dolphins",
  "Octopus",
  "Whales",
  "Jellyfish",
  "Shark Week",
  "Treasure maps",
  "Pirates",
  "Pirate ships",
  "Mermaids",
  "Atlantis",
  "Greek gods",
  "Zeus",
  "Hercules",
  "Pegasus",
  "Olympus",
  "Percy Jackson",
  "Archery",
  "Horseback riding",
  "Building forts",
  "Camping",
  "Bonfires",
  "S'mores",
  "Fishing",
  "Hiking",
  "Rock climbing",
  "Trampolines",
  "Bounce houses",
  "Jungle gyms",
  "Nerf battles",
  "Water balloon fights",
  "Laser tag",
  "Dodgeball",
  "Tag",
  "Hide and seek",
  "Bugs Bunny",
  "Daffy Duck",
  "Sylvester",
  "Tweety",
  "Road Runner",
  "Wile E. Coyote",
  "Tiny Toons",
  "Animaniacs",
  "Yakko",
  "Wakko",
  "Dot",
  "Bendy and the Ink Machine",
  "Pac-Man",
  "Ghostbusters",
  "Slimer",
  "Ghosts",
  "Mummies",
  "Pharaohs",
  "Ancient Egypt",
  "Pyramids",
  "Sphinx",
  "Indiana Jones",
  "Explorers",
  "Treasure hunters",
  "Gold mines",
  "Skiing",
  "Snowboarding",
  "Ice skating",
  "Snowball fights",
  "Building snowmen",
  "Igloos",
  "Penguins",
  "Polar bears",
  "Arctic explorers",
  "North Pole",
  "Santa Claus",
  "Reindeers",
  "Christmas elves",
  "Frosty the Snowman",
  "Snowflakes",
  "Snow globes",
  "Winter sports",
  "Olympics",
  "Gymnastics",
  "Swimming",
  "Diving",
  "Track and field",
  "Soccer",
  "Ping pong",
  "Karate",
  "Judo",
  "Martial arts",
  "Kung fu",
  "Ninjas",
  "Samurai",
  "Lightsabers",
  "Star Trek",
  "Starfleet",
  "Starships",
  "Black holes",
  "Galaxies",
  "Planets",
  "Moon landing",
  "Lunar rover",
  "Spacesuits",
  "Jetpacks",
  "Video game streaming",
  "YouTube",
  "Let's Plays",
  "Funny cat videos",
  "ASMR videos",
  "Cartoon Network",
  "Nickelodeon",
  "Disney Channel",
  "PBS Kids",
  "Wild Kratts",
  "Animal documentaries",
  "National Geographic Kids",
  "Weather balloons",
  "Tornadoes",
  "Hurricanes",
  "Earthquakes",
  "Tectonic plates",
  "Volcanic eruptions",
  "Lava",
  "Earth's core",
  "Meteor showers",
  "Shooting stars",
  "Northern lights",
  "Saturn's rings",
  "Mars rovers",
  "Alien civilizations",
  "UFOs",
  "Rocket ships",
  "Space stations",
  "ISS (International Space Station)",
  "NASA",
  "Moon rocks",
  "Asteroids",
  "Comets",
  "Meteorites",
  "Robot building kits",
  "STEM activities",
  "Chemistry sets",
  "Physics experiments",
  "Electric circuits",
  "Magnets",
  "Dinobot transformers",
  "Iron Man suit",
  "Spider sense",
  "Superman’s strength",
  "Invisible cloak",
  "Hogwarts",
  "Griffin",
  "Phoenix",
  "Hippogriff",
  "Centaurs",
  "Talking animals",
  "Time machines",
  "Teleportation",
  "Parallel universes",
  "Super speed",
  "Invisibility",
  "Magic potions",
  "Magic school buses",
  "School of rock",
  "Ballet",
  "Tap dancing",
  "Hip-hop dance",
  "Breakdancing",
  "Jazz hands",
  "Singing competitions",
  "Talent shows",
  "Puppetry",
  "Ventriloquism",
  "Face painting",
  "Costume parties",
  "Zombie costumes",
  "Werewolves",
  "Vampires",
  "Haunted houses",
  "Monster trucks",
  "Hot air balloons",
  "Kites",
  "Paper airplanes",
  "Origami dragons",
  "Rubik's cube",
  "Jigsaw puzzles",
  "Word searches",
  "Crosswords",
  "Mazes",
  "Optical illusions",
  "Magic eye puzzles",
  "Mandalas",
  "Symmetry",
  "Fractals",
  "Infinity",
  "Fidget spinners",
  "Rubber bands",
  "Silly bands",
  "Squishy toys",
  "Stress balls",
  "Glow sticks",
  "Bouncy balls",
  "Slinky",
  "Yo-yos",
  "Hula hoops",
  "Jump ropes",
  "Double Dutch",
  "Parachutes",
  "Model rockets",
  "Drones",
  "Remote control cars",
  "Remote control helicopters",
  "Tamagotchis",
  "Virtual pets",
  "Pet dinosaurs",
  "Sea Monkeys",
  "Pet turtles",
  "Goldfish",
  "Hamsters",
  "Guinea pigs",
  "Parakeets",
  "Bird watching",
  "Tree houses",
  "Fairy houses",
  "Gnome villages",
  "Miniature gardens",
  "Mazes of mirrors",
  "Haunted corn mazes",
  "Pumpkin carving",
  "Scarecrows",
  "Halloween costumes",
  "Vampire teeth",
  "Witch hats",
  "Jack-o'-lanterns",
  "Spooky stories",
  "Campfire songs",
  "Ghost stories",
  "Graveyard exploration",
  "Archaeology",
  "Fossils",
  "Dinosaur bones",
  "T-Rex skeletons",
  "Paleontology",
  "Museum visits",
  "Planetarium shows",
  "Dinosaur exhibits",
  "Space exhibits",
  "Ancient artifacts",
  "Fossil hunting",
  "Geode collecting",
  "Rock collecting",
  "Crystal collecting",
  "Seashell collecting",
  "Butterfly gardens",
  "Zoo trips",
  "Aquarium visits",
  "Petting zoos",
  "Farm animals",
  "Cowboy hats",
  "Barnyard animals",
  "Beekeeping",
  "Honeycomb",
  "Water slides",
  "Splash parks",
  "Kiddie pools",
  "Tree climbing",
  "Bird nests",
  "Animal tracks",
  "Footprints",
  "Treasure hunts",
  "Scavenger hunts",
  "Magnifying glasses",
  "Spy gadgets",
  "Secret agents",
  "Walkie-talkies",
  "Invisible ink",
  "Secret codes",
  "Detectives",
  "Sherlock Holmes",
  "Escape rooms",
  "Clue games",
  "Solving mysteries",
  "Magic shows",
  "Card tricks",
  "Juggling",
  "Circus acts",
  "Clowns",
  "Acrobats",
  "Tightrope walking",
  "Flying trapeze",
  "Carnivals",
  "Ferris wheels",
  "Bumper cars",
  "Roller coasters",
  "Haunted house rides",
  "Carousel rides",
  "Cotton candy",
  "Popcorn",
  "Snow cones",
  "Balloon animals",
  "Parades",
  "Fireworks",
  "Fourth of July",
  "Veterans Day",
  "Thanksgiving parades",
  "Christmas parades",
  "Holiday lights",
  "Gingerbread houses",
  "Cookie decorating",
  "Chocolate making",
  "Ice cream sundaes",
  "Milkshakes",
  "Cupcake decorating",
  "Cake pops",
  "Candy making",
  "Lollipops",
  "Gummy bears",
  "Marshmallows",
  "Hot chocolate",
  "Ice cream trucks",
  "Funnel cakes",
  "Churros",
  "Pretzels",
  "Cotton candy machines",
  "Snow cone machines",
  "Pizza parties",
  "Taco Tuesdays",
  "Burger grilling",
  "Backyard BBQ",
  "Cornhole",
  "Lawn darts",
  "Water guns",
  "Super Soakers",
  "Slip 'n slides",
  "Beach balls",
  "Sandcastles",
  "Beach volleyball",
  "Tide pools",
  "Crab catching",
  "Starfish",
  "Sea urchins",
  "Shellfish",
  "Fishing nets",
  "Kayaking",
  "Canoeing",
  "Paddleboarding",
  "Rowboats",
  "Boating",
  "Jet skiing",
  "Sailing",
  "Treasure islands",
  "Mermaid lagoons",
  "Shipwrecks",
  "Scuba diving",
  "Snorkeling",
  "Underwater caves",
  "Deep sea diving",
  "Marine biology",
  "Shark cages",
  "Dolphin watching",
  "Whale watching",
  "Safari trips",
  "Elephants",
  "Lions",
  "Tigers",
  "Giraffes",
  "Zebras",
  "Cheetahs",
  "Rhinos",
  "Hippos",
  "Jungle animals",
  "Toucans",
  "Parrots",
  "Monkeys",
  "Gorillas",
  "Orangutans",
  "Chimps",
  "Jungle adventures",
  "Treehouses",
  "Jungle vines",
  "Jungle explorers",
  "Tarzan",
  "Jane",
  "Jungle books",
  "Waterfalls",
  "Rainforests",
  "Amazon River",
  "Canoeing trips",
  "Jungle safaris",
  "Rafting",
  "Rapids",
  "Volcano climbing",
  "National parks",
  "Camping trips",
  "Tent building",
  "Marshmallow roasting",
  "Stargazing",
  "Telescope viewing",
  "Constellations",
  "Milky Way",
  "Comet sightings",
  "Alien encounters",
  "UFO sightings",
  "Mars colonies",
  "Moon bases",
  "Asteroid belts",
  "Rover expeditions",
  "Galaxy exploration",
  "Starship adventures",
  "Star charts",
  "Astronomy",
  "Rocket launches",
  "Lunar landings",
  "Solar systems",
  "Exoplanets",
  "Wormholes",
  "Multiverses",
  "Iron Man",
  "Captain America",
  "Thor",
  "Hulk",
  "Black Widow",
  "Hawkeye",
  "Guardians of the Galaxy",
  "Rocket Raccoon",
  "Groot",
  "Star-Lord",
  "Gamora",
  "Drax",
  "Thanos",
  "Infinity Stones",
  "Doctor Strange",
  "Magic portals",
  "Venom",
  "Green Goblin",
  "Sandman",
  "Lizard",
  "Electro",
  "Mysterio",
  "Joker",
  "Harley Quinn",
  "Penguin",
  "Catwoman",
  "Riddler",
  "Superman",
  "Lex Luthor",
  "Flash",
  "Cyborg",
  "Green Lantern",
  "Justice League",
  "Robin",
  "Starfire",
  "Beast Boy",
  "Raven",
  "Gotham City",
  "Metropolis",
  "Amazon Warriors",
  "Invisible jet",
  "Batmobile",
  "Wayne Enterprises",
  "Fortress of Solitude",
  "Kryptonite",
  "Alien invasions",
  "Super strength",
  "Laser eyes",
  "X-ray vision",
  "Flight",
  "Super intelligence",
  "Gadgets",
  "Utility belt",
  "Bat signal",
  "Web shooters",
  "Spidey sense",
  "Shield throwing",
  "Mjolnir",
  "Asgard",
  "Odin",
  "Loki",
  "Valkyries",
  "Frost giants",
  "Bifrost",
  "Quantum realm",
  "Pym particles",
  "Ant-Man",
  "Wasp",
  "Time heist",
  "Infinity Gauntlet",
  "Avengers Tower",
  "X-Men",
  "Wolverine",
  "Professor X",
  "Magneto",
  "Cyclops",
  "Storm",
  "Jean Grey",
  "Mystique",
  "Beast",
  "Quicksilver",
  "Deadpool",
  "Logan",
  "Sabretooth",
  "Juggernaut",
  "Mutants",
  "Sentinels",
  "Danger Room",
  "Cerebro",
  "Krakoa",
  "Weapon X",
  "Claws",
  "Healing factor",
  "Adamantium",
  "Mutant powers",
  "X-gene",
  "Supervillains",
  "Doomsday",
  "Darkseid",
  "Brainiac",
  "Bizarro",
  "Apokolips",
  "New Gods",
  "Omega beams",
  "Boom tubes",
  "Astronomy club",
  "Meteorology",
  "Rock climbing walls",
  "Birdhouses",
  "Wildlife conservation",
  "Eco-friendly activities",
  "Recycling projects",
  "Solar energy kits",
  "Wind turbines",
  "Sustainability",
  "Gardening vegetables",
  "Urban farming",
  "Composting",
  "Worm farms",
  "Solar ovens",
  "Weather tracking",
  "Cloud watching",
  "Rain gauges",
  "Tsunamis",
  "Nature walks",
  "Tree identification",
  "Planting trees",
  "Camping survival skills",
  "Building shelters",
  "Animal footprints",
  "Whale songs",
  "Animal rescues",
  "Adopt-a-pet",
  "Foster pets",
  "Horse grooming",
  "Wildlife photography",
  "Insect study",
  "Ant farms",
  "Butterfly metamorphosis",
  "Beehive building",
  "Star gazing",
  "Planet identification",
  "Rocket building",
  "Moon phases",
  "Constellation mapping",
  "Navigating with stars",
  "Sundials",
  "Science experiments",
  "Solar system models",
  "Gravity experiments",
  "DNA models",
  "Human anatomy",
  "Bones and skeletons",
  "X-rays",
  "Microscope slides",
  "Germs and bacteria",
  "Tissue samples",
  "Virus models",
  "Water filtration",
  "Nature documentaries",
  "Insect collecting",
  "Shellfish biology",
  "Endangered species",
  "National parks tours",
  "Virtual museum tours",
  "Fossil digs",
  "Dinosaur digs",
  "Robotics kits",
  "AI for kids",
  "Drone programming",
  "3D printing",
  "Circuit building",
  "Arduino",
  "Raspberry Pi",
  "STEM toys",
  "Mathematical puzzles",
  "Rubik's cubes",
  "Origami engineering",
  "Paper airplane challenges",
  "Bridge building",
  "Lego engineering",
  "Marble runs",
  "Dominoes chain reactions",
  "Woodworking kits",
  "Soap carving",
  "Clay modeling",
  "Pottery",
  "Knitting",
  "Crocheting",
  "Sewing buttons",
  "Embroidery",
  "Quilting",
  "Patchwork",
  "Weaving",
  "Basket weaving",
  "Herb gardens",
  "Seed planting",
  "Botanical gardens",
  "Succulents",
  "Water plants",
  "Cactus gardens",
  "Bonsai trees",
  "Flower pressing",
  "Herbarium",
  "Terrariums",
  "Aquascaping",
  "Aquatic plants",
  "Desert ecosystems",
  "Rainforest ecosystems",
  "Wildlife tracking",
  "Hiking trails",
  "Park ranger activities",
  "Camping knots",
  "Fishing knots",
  "Tracking wildlife",
  "Animal behavior",
  "Bird migration",
  "Fungi identification",
  "Mushroom foraging",
  "Edible plants",
  "Foraging",
  "First aid skills",
  "Compass navigation",
  "Map reading",
  "Orienteering",
  "Geocaching",
  "Letterboxing",
  "Sculpting",
  "Model building",
  "Miniature models",
  "Railroad building",
  "Model cars",
  "Model planes",
  "Ship in a bottle",
  "Kite making",
  "Wind chimes",
  "Suncatchers",
  "Jewelry making",
  "Beadwork",
  "Macrame",
  "Friendship bracelets",
  "Rock tumbling",
  "Geode breaking",
  "Crystal growing",
  "Sand art",
  "Mosaic art",
  "Tiling",
  "Stamp collecting",
  "Coin collecting",
  "Postcard collecting",
  "Vintage toys",
  "Retro games",
  "Pen pals",
  "Postcard writing",
  "Calligraphy",
  "Handwriting improvement",
  "Sign language",
  "Braille",
  "Bookbinding",
  "Origami animals",
  "Shadow puppets",
  "Paper mache",
  "Leaf pressing",
  "Rock painting",
  "Pebble art",
  "Shell art",
  "Nature crafts",
  "Stargazing journals",
  "Weather diaries",
  "Dream journals",
  "Book clubs",
  "Storytelling",
  "Fairytale writing",
  "Poetry writing",
  "Short stories",
  "Creative writing",
  "Comic books",
  "Illustrating comics",
  "Cartooning",
  "Character design",
  "Digital painting",
  "Game design",
  "Storyboarding",
  "Stop motion animation",
  "Flipbooks",
  "Voice acting",
  "Audio stories",
  "Shadow theater",
  "Musical instruments",
  "Drum circles",
  "Percussion instruments",
  "Wind instruments",
  "Ukulele",
  "Piano",
  "Keyboard",
  "Synthesizers",
  "DJing",
  "Beatboxing",
  "Vocal warm-ups",
  "Singing lessons",
  "Choir",
  "Marching band",
  "Rhythmic gymnastics",
  "Ribbon dancing",
  "Gymnastics tricks",
  "Balance beams",
  "Springboards",
  "Parallel bars",
  "Vaulting",
  "Pole vaulting",
  "Shot put",
  "Hammer throw",
  "Discus",
  "Track races",
  "Relay races",
  "High jump",
  "Long jump",
  "Triple jump",
  "Javelin throw",
  "Fencing",
  "Sword fighting",
  "Taekwondo",
  "Karate forms",
  "Martial arts tournaments",
  "Self-defense",
  "Boxing",
  "Wrestling",
  "Sumo wrestling",
  "Tug of war",
  "Rowing",
  "Canoe racing",
  "Kayaking races",
  "Dragon boat racing",
  "Sailing regattas",
  "Underwater robotics",
  "Scuba gear",
  "Snorkeling gear",
  "Deep sea exploration",
  "Coral conservation",
  "Sea turtle rescue",
  "Shark research",
  "Octopus habitats",
  "Jellyfish studies",
  "Marine mammal studies",
  "Penguin colonies",
  "Antarctic expeditions",
  "Arctic wildlife",
  "Ice fishing",
  "Igloo building",
  "Snow forts",
  "Snow tunnels",
  "Ice sculptures",
  "Snowflake science",
  "Glacier studies",
  "Alpine ecosystems",
  "Mountain weather",
  "Mountain climbing",
  "Mountaineering gear",
  "Ice climbing",
  "Avalanche safety",
  "Snowshoeing",
  "Cross-country skiing",
  "Sledding",
  "Dog sledding",
  "Ski jumping",
  "Snowboarding tricks",
  "Half-pipes",
  "Slalom skiing",
  "Ice skating routines",
  "Figure skating",
  "Speed skating",
  "Hockey drills",
  "Luge",
  "Bobsledding",
  "Curling",
  "Zamboni machines",
  "Hockey pucks",
  "Ice rinks",
  "Frozen lakes",
  "Arctic expeditions",
  "Polar research",
  "Blubber experiments",
  "Thermal insulation",
  "Heat transfer",
  "Wind chill",
  "Solar radiation",
  "Greenhouse gases",
  "Carbon footprints",
  "Sustainable living",
  "Eco-friendly homes",
  "Tiny houses",
  "Off-the-grid living",
  "Water conservation",
  "Rainwater harvesting",
  "Solar panels",
  "Wind farms",
  "Composting toilets",
  "Upcycling",
  "Trash collecting",
  "Marine debris",
  "Beach clean-ups",
  "Coral reef protection",
  "Ocean acidification",
  "Mangrove restoration",
  "Wildlife corridors",
  "Endangered species conservation",
  "Rainforest preservation",
  "Deforestation prevention",
  "Animal rehabilitation",
  "Graphic design",
  "Video editing",
  "Podcasting",
  "Vlogging",
  "YouTube channels",
  "Twitch streaming",
  "Content creation",
  "Video production",
  "Digital photography",
  "Film making",
  "Short films",
  "Animation",
  "2D animation",
  "3D modeling",
  "Motion graphics",
  "Illustration",
  "Concept art",
  "Fan art",
  "Manga drawing",
  "Anime art",
  "Webcomics",
  "Graphic novels",
  "Light novels",
  "Screenwriting",
  "Procreate",
  "Photoshop",
  "Blender",
  "Adobe After Effects",
  "Final Cut Pro",
  "Premiere Pro",
  "Video game design",
  "Game development",
  "Unity",
  "Unreal Engine",
  "Roblox Studio",
  "Minecraft modding",
  "Game coding",
  "Python",
  "Java",
  "C++",
  "HTML",
  "CSS",
  "JavaScript",
  "Web development",
  "App development",
  "iOS development",
  "Android app development",
  "AI programming",
  "Machine learning",
  "Augmented reality",
  "Virtual reality",
  "UX/UI design",
  "CAD software",
  "Laser cutting",
  "Product design",
  "Prototyping",
  "Robotics",
  "Arduino projects",
  "Raspberry Pi projects",
  "Drone flying",
  "RC cars",
  "Electric scooters",
  "DIY electronics",
  "Tech reviews",
  "Gadget unboxing",
  "Tech blogs",
  "Startups",
  "Entrepreneurship",
  "E-commerce",
  "Dropshipping",
  "Stock market investing",
  "Cryptocurrency",
  "NFT art",
  "Blockchain",
  "Personal finance",
  "Budgeting",
  "Freelancing",
  "Thrift shopping",
  "Vintage fashion",
  "Streetwear",
  "Sneaker culture",
  "Shoe customization",
  "Cosplay",
  "Costume design",
  "Sewing cosplay",
  "Prop making",
  "3D printed props",
  "Comic conventions",
  "Anime conventions",
  "Esports tournaments",
  "League of Legends",
  "Dota 2",
  "Fortnite",
  "Valorant",
  "Call of Duty",
  "Minecraft speedruns",
  "FIFA",
  "NBA 2K",
  "Rocket League",
  "Super Smash Bros.",
  "Mario Kart",
  "Gaming clans",
  "Gaming merchandise",
  "Board game nights",
  "Tabletop RPGs",
  "Dungeons & Dragons",
  "Magic: The Gathering",
  "Pokemon trading cards",
  "Yu-Gi-Oh!",
  "Beyblade battles",
  "K-pop",
  "BTS",
  "Blackpink",
  "Stray Kids",
  "K-dramas",
  "Anime",
  "Naruto",
  "One Piece",
  "Attack on Titan",
  "My Hero Academia",
  "Demon Slayer",
  "Haikyuu!!",
  "Tokyo Ghoul",
  "Sword Art Online",
  "JoJo's Bizarre Adventure",
  "Dragon Ball Z",
  "Fullmetal Alchemist",
  "Hunter x Hunter",
  "Studio Ghibli",
  "Totoro",
  "Spirited Away",
  "Howl's Moving Castle",
  "Your Name",
  "Weathering with You",
  "Shonen Jump",
  "Crunchyroll",
  "Funimation",
  "Manga collections",
  "Shoujo manga",
  "Seinen manga",
  "Visual novels",
  "K-pop dance covers",
  "TikTok challenges",
  "Dance choreography",
  "Hip hop dance",
  "Popping and locking",
  "Freestyle dance",
  "Jazz dance",
  "Contemporary dance",
  "Lyrical dance",
  "Dance competitions",
  "TikTok trends",
  "Instagram reels",
  "Snapchat streaks",
  "Twitter hashtags",
  "Viral memes",
  "Influencer marketing",
  "Social media branding",
  "Photography",
  "Street photography",
  "Portrait photography",
  "Drone photography",
  "Astrophotography",
  "Photojournalism",
  "Lightroom",
  "Darkroom photography",
  "Film cameras",
  "Vintage cameras",
  "Polaroids",
  "Photoshoots",
  "Portfolio building",
  "Graphic t-shirt design",
  "Merch drops",
  "Limited-edition sneakers",
  "Sneaker flipping",
  "Pop culture merchandise",
  "Statue collecting",
  "Fan fiction",
  "Wattpad stories",
  "Character development",
  "World building",
  "Fantasy writing",
  "Sci-fi writing",
  "Dystopian fiction",
  "Post-apocalyptic novels",
  "Young adult novels",
  "Horror fiction",
  "Psychological thrillers",
  "Crime dramas",
  "True crime documentaries",
  "Radio shows",
  "Music production",
  "GarageBand",
  "FL Studio",
  "Ableton",
  "SoundCloud",
  "Music playlists",
  "Lo-fi beats",
  "Synthwave",
  "Vaporwave",
  "EDM",
  "Trap music",
  "Hip hop beats",
  "Songwriting",
  "Lyricism",
  "Music covers",
  "Acoustic guitar",
  "Electric guitar",
  "Drumming",
  "A cappella",
  "Choir singing",
  "Musical theater",
  "Broadway shows",
  "Playwriting",
  "Stage directing",
  "Cinematography",
  "Lighting design",
  "Set design",
  "Makeup artistry",
  "Special effects makeup",
  "Wig styling",
  "Drag culture",
  "Vogueing",
  "LGBTQ+ activism",
  "Pride parades",
  "Social justice movements",
  "Environmental activism",
  "Climate change awareness",
  "Sustainable fashion",
  "Fast fashion alternatives",
  "Eco-friendly brands",
  "Zero-waste lifestyle",
  "Minimalism",
  "Mindfulness",
  "Meditation apps",
  "Yoga",
  "Pilates",
  "Strength training",
  "CrossFit",
  "Obstacle courses",
  "Spartan races",
  "Marathons",
  "Trail running",
  "Cycling",
  "Mountain biking",
  "Parkour",
  "Bouldering",
  "Surfing",
  "Kiteboarding",
  "Windsurfing",
  "Wakeboarding",
  "Skimboarding",
  "Indoor rock climbing",
  "Roller skating",
  "Roller derby",
  "Ice hockey",
  "Equestrian sports",
  "Show jumping",
  "Dressage",
  "Pet training",
  "Dog shows",
  "Animal shelters",
  "Wildlife volunteering",
  "Shark conservation",
  "Astronomy clubs",
  "Star maps",
  "Astrobiology",
  "Space colonies",
  "Mars exploration",
  "Lunar bases",
  "NASA programs",
  "SpaceX launches",
  "Quantum physics",
  "String theory",
  "Time travel theories",
  "Multiverse theory",
  "Artificial intelligence",
  "Self-driving cars",
  "Smart homes",
  "Wearable tech",
  "Virtual assistants",
  "Biohacking",
  "Cognitive science",
  "Neuroscience",
  "Mental health awareness",
  "Mindfulness practices",
  "Psychology experiments",
  "Brain training",
  "Memory improvement",
  "Sleep science",
  "Lucid dreaming",
  "Astral projection",
  "Conspiracy theories",
  "Urban legends",
  "Paranormal investigations",
  "Ghost hunting",
  "Cryptozoology",
  "Bigfoot sightings",
  "UFO research",
  "Alien abductions",
  "Area 51",
  "Extraterrestrial life",
  "Space-time continuum",
  "Interdimensional travel",
  "Psychic abilities",
  "Telekinesis",
  "Mind reading",
  "Astral travel",
  "Past life regression",
  "Aura reading",
  "Chakras",
  "Reiki healing",
  "Crystal healing",
  "Tarot readings",
  "Palmistry",
  "Numerology",
  "Zodiac signs",
  "Horoscopes",
  "Star signs",
  "Birth charts",
  "Planetary alignment",
  "Stranger Things",
  "The Umbrella Academy",
  "Riverdale",
  "13 Reasons Why",
  "The Mandalorian",
  "The Witcher",
  "Outer Banks",
  "Euphoria",
  "The 100",
  "Teen Wolf",
  "The Vampire Diaries",
  "Legacies",
  "Shadowhunters",
  "Cobra Kai",
  "Locke & Key",
  "Arrow",
  "Supergirl",
  "Legends of Tomorrow",
  "The Boys",
  "Invincible",
  "The Falcon and the Winter Soldier",
  "WandaVision",
  "Ms. Marvel",
  "Moon Knight",
  "Daredevil",
  "Jessica Jones",
  "Luke Cage",
  "Iron Fist",
  "The Defenders",
  "The Punisher",
  "Spider-Man: No Way Home",
  "Black Panther",
  "Avengers: Endgame",
  "Thor: Ragnarok",
  "Shang-Chi",
  "Captain Marvel",
  "Suicide Squad",
  "The Batman",
  "Fantastic Beasts",
  "The Hunger Games",
  "Maze Runner",
  "Divergent",
  "Twilight",
  "The Maze Runner",
  "The Fault in Our Stars",
  "To All the Boys I've Loved Before",
  "The Kissing Booth",
  "Love, Simon",
  "Five Feet Apart",
  "After",
  "All the Bright Places",
  "The Perks of Being a Wallflower",
  "Me and Earl and the Dying Girl",
  "A Silent Voice",
  "I Want to Eat Your Pancreas",
  "Princess Mononoke",
  "My Neighbor Totoro",
  "The Wind Rises",
  "The Boy and the Beast",
  "Wolf Children",
  "Summer Wars",
  "One Punch Man",
  "Boruto",
  "Dragon Ball Super",
  "Fullmetal Alchemist: Brotherhood",
  "Death Note",
  "Bleach",
  "Black Clover",
  "Fairy Tail",
  "Mob Psycho 100",
  "Blue Exorcist",
  "Assassination Classroom",
  "The Promised Neverland",
  "Jujutsu Kaisen",
  "Chainsaw Man",
  "Re:Zero",
  "No Game No Life",
  "That Time I Got Reincarnated as a Slime",
  "Overlord",
  "Konosuba",
  "Fruits Basket",
  "Horimiya",
  "Toradora!",
  "Ouran High School Host Club",
  "Yuri on Ice",
  "Kuroko's Basketball",
  "Free!",
  "The Seven Deadly Sins",
  "Beastars",
  "Bungou Stray Dogs",
  "Dr. Stone",
  "Fire Force",
  "The Rising of the Shield Hero",
  "Erased",
  "Steins;Gate",
  "Cowboy Bebop",
  "Neon Genesis Evangelion",
  "Akira",
  "Ghost in the Shell",
  "Psycho-Pass",
  "Code Geass",
  "Gurren Lagann",
  "Parasyte",
  "Kill la Kill",
  "Attack on Titan movies",
  "Demon Slayer: Mugen Train",
  "Naruto: The Last",
  "One Piece Film: Red",
  "Dragon Ball Super: Broly",
  "My Hero Academia: Heroes Rising",
  "Digimon",
  "Cardcaptor Sakura",
  "Sailor Moon",
  "Inuyasha",
  "Raya and the Last Dragon",
  "Encanto",
  "Moana",
  "Coco",
  "Inside Out",
  "Luca",
  "Turning Red",
  "The Incredibles",
  "The LEGO Movie",
  "Wreck-It Ralph",
  "The Secret Life of Pets",
  "Sing",
  "Hotel Transylvania",
  "Monster House",
  "Coraline",
  "The Nightmare Before Christmas",
  "Corpse Bride",
  "Kubo and the Two Strings",
  "The Croods",
  "Epic",
  "Rise of the Guardians",
  "Cloudy with a Chance of Meatballs",
  "Meet the Robinsons",
  "Megamind",
  "Monsters, Inc.",
  "The Good Dinosaur",
  "Brave",
  "Bolt",
  "Atlantis: The Lost Empire",
  "Treasure Planet",
  "Lilo & Stitch",
  "The Lion King",
  "Aladdin",
  "Mulan",
  "Beauty and the Beast",
  "The Hunchback of Notre Dame",
  "The Little Mermaid",
  "Peter Pan",
  "Alice in Wonderland",
  "Sleeping Beauty",
  "Cinderella",
  "Pocahontas",
  "The Jungle Book",
  "Pinocchio",
  "Dumbo",
  "Bambi",
  "Fantasia",
  "Lady and the Tramp",
  "101 Dalmatians",
  "The Aristocats",
  "Oliver & Company",
  "Robin Hood",
  "The Sword in the Stone",
  "The Rescuers",
  "Zombieland",
  "Pacific Rim",
  "Godzilla",
  "King Kong",
  "War of the Worlds",
  "Independence Day",
  "Edge of Tomorrow",
  "The Matrix",
  "Ready Player One",
  "Inception",
  "Interstellar",
  "The Martian",
  "Gravity",
  "Pirates of the Caribbean",
  "Lord of the Rings",
  "The Hobbit",
  "Game of Thrones",
  "House of the Dragon",
  "The Walking Dead",
  "Breaking Bad",
  "Better Call Saul",
  "Sherlock",
  "Doctor Who",
  "Supernatural",
  "The X-Files",
  "The Twilight Zone",
  "The Crown",
  "Peaky Blinders",
  "The Queen's Gambit",
  "Sex Education",
  "The Haunting of Hill House",
  "Chilling Adventures of Sabrina",
  "The Society",
  "The Order",
  "Cooking",
  "Traveling",
  "Gaming",
  "Reading",
  "Writing",
  "Painting",
  "Sewing",
  "Woodworking",
  "Metalworking",
  "Leathercraft",
  "Birdwatching",
  "Backpacking",
  "Running",
  "Skating",
  "Rock Climbing",
  "Scuba Diving",
  "Shooting",
  "Hunting",
  "Horseback Riding",
  "Motorcycling",
  "Car Restoration",
  "Auto Racing",
  "Drone Flying",
  "Flying (Pilot)",
  "Chess",
  "Checkers",
  "Board Games",
  "Card Games",
  "Magic Tricks",
  "Sudoku",
  "Crossword Puzzles",
  "Jigsaw Puzzles",
  "Roleplaying Games (RPGs)",
  "Dungeons and Dragons",
  "LARPing",
  "Tabletop Wargaming",
  "Warhammer",
  "Model Building",
  "RC Cars",
  "RC Planes",
  "RC Boats",
  "Collecting Stamps",
  "Collecting Coins",
  "Collecting Antiques",
  "Collecting Toys",
  "Collecting Action Figures",
  "Collecting Cards",
  "Collecting Vinyl Records",
  "Antiquing",
  "Thrifting",
  "DIY Projects",
  "Home Improvement",
  "Interior Design",
  "Architecture",
  "Furniture Restoration",
  "Jewelry Making",
  "Soap Making",
  "Candle Making",
  "Perfume Making",
  "Bonsai Cultivation",
  "Herpetoculture (Reptile Keeping)",
  "Fishkeeping",
  "Aquarium Design",
  "Home Brewing",
  "Wine Making",
  "Cocktail Mixing",
  "Baking",
  "Grilling",
  "Barbecue",
  "Cake Decorating",
  "Chocolate Making",
  "Cheese Making",
  "Pickling",
  "Canning",
  "Fermenting",
  "Butchery",
  "Charcuterie",
  "Sausage Making",
  "Fitness Training",
  "Weightlifting",
  "Meditation",
  "Martial Arts",
  "Jiu-Jitsu",
  "Kickboxing",
  "MMA",
  "Sword Fighting",
  "Kendo",
  "Tai Chi",
  "Zumba",
  "Dance",
  "Tap Dance",
  "Ballroom Dance",
  "Salsa",
  "Tango",
  "Swing Dance",
  "Hip Hop Dance",
  "Modern Dance",
  "Folk Dance",
  "Line Dancing",
  "Square Dancing",
  "Ice Skating",
  "Figure Skating",
  "Roller Skating",
  "Rollerblading",
  "Longboarding",
  "Scootering",
  "Slacklining",
  "Trampolining",
  "Cheerleading",
  "Team Sports",
  "Baseball",
  "Softball",
  "Tennis",
  "Badminton",
  "Squash",
  "Table Tennis",
  "Volleyball",
  "Beach Volleyball",
  "Golf",
  "Bowling",
  "Billiards",
  "Snooker",
  "Darts",
  "Paintball",
  "Laser Tag",
  "Airsoft",
  "Frisbee",
  "Disc Golf",
  "Ultimate Frisbee",
  "Rugby",
  "Cricket",
  "Lacrosse",
  "Field Hockey",
  "Ice Hockey",
  "Crew",
  "Synchronized Swimming",
  "Water Polo",
  "Pole Vaulting",
  "Javelin",
  "Shot Put",
  "High Jump",
  "Long Jump",
  "Triple Jump",
  "Pole Dancing",
  "Street Dancing",
  "Treasure Hunting",
  "Metal Detecting",
  "Survival Skills",
  "Bushcraft",
  "Lock Picking",
  "Escape Rooms",
  "Tattooing",
  "Body Painting",
  "Henna Art",
  "Face Painting",
  "Lettering",
  "Typography",
  "Graphic Design",
  "Web Design",
  "Coding",
  "App Development",
  "3D Printing",
  "Virtual Reality",
  "Augmented Reality",
  "Blogging",
  "YouTubing",
  "Streaming",
  "Social Media Management",
  "Influencing",
  "Public Speaking",
  "Debating",
  "Speech Writing",
  "Stand-Up Comedy",
  "Improv Comedy",
  "Acting",
  "Theater",
  "Film Making",
  "Directing",
  "Video Editing",
  "Voice Acting",
  "Music Production",
  "Singing",
  "Playing Guitar",
  "Playing Piano",
  "Playing Drums",
  "Playing Violin",
  "Playing Saxophone",
  "Playing Trumpet",
  "Playing Flute",
  "Playing Clarinet",
  "Playing Harmonica",
  "Playing Ukulele",
  "Playing Bass",
  "Playing Cello",
  "Playing Mandolin",
  "Playing Banjo",
  "Composing Music",
  "Karaoke",
  "Opera Singing",
  "Choir Singing",
  "Music Collecting",
  "Concert Going",
  "Festival Attendance",
  "Wildlife Photography",
  "Nature Walks",
  "Environmental Activism",
  "Volunteering",
  "Community Service",
  "Mentoring",
  "Tutoring",
  "Language Learning",
  "Sign Language",
  "Foreign Cultures",
  "History",
  "Genealogy",
  "Mythology",
  "UFO Hunting",
  "Paranormal Investigation",
  "Conspiracy Theories",
  "True Crime",
  "Urban Exploration",
  "Ghost Hunting",
  "Tarot Reading",
  "Crystal Healing",
  "Reiki",
  "Energy Healing",
  "Holistic Health",
  "Herbalism",
  "Acupuncture",
  "Alternative Medicine",
  "Breathwork",
  "Chakra Balancing",
  "Spirituality",
  "Religion",
  "Philosophy",
  "Political Activism",
  "Human Rights Advocacy",
  "Animal Rights Advocacy",
  "Environmental Conservation",
  "Sustainable Living",
  "Zero Waste Living",
  "Van Life",
  "Tiny House Living",
  "RVing",
  "Boat Building",
  "Ship Restoration",
  "Piracy (fictional)",
  "Scouting",
  "Caving",
  "Speleology",
  "Mineralogy",
  "Fossil Hunting",
  "Rock Tumbling",
  "Gemology",
  "Lapidary Arts",
  "Jade Carving",
  "Mountaineering",
  "Volcanology",
  "Seismology",
  "Oceanography",
  "Cosmology",
  "Astrophysics",
  "Quantum Physics",
  "Theoretical Physics",
  "Chemistry",
  "Biochemistry",
  "Genetics",
  "Microbiology",
  "Entomology",
  "Botany",
  "Zoology",
  "Marine Biology",
  "Ecology",
  "Evolutionary Biology",
  "Behavioral Science",
  "Psychology",
  "Sociology",
  "Anthropology",
  "Linguistics",
  "Ethnomusicology",
  "Cultural Studies",
  "Literary Analysis",
  "Creative Writing",
  "Poetry",
  "Novels",
  "Short Stories",
  "Journalism",
  "Reporting",
  "Investigative Journalism",
  "War Correspondence",
  "Freelance Writing",
  "Copywriting",
  "Technical Writing",
  "Editing",
  "Proofreading",
  "Public Relations",
  "Marketing",
  "Brand Management",
  "Event Planning",
  "Fundraising",
  "Business Strategy",
  "Investing",
  "Real Estate",
  "Stock Trading",
  "Blockchain Technology",
  "Economics",
  "Data Science",
  "Machine Learning",
  "Artificial Intelligence",
  "Deep Learning",
  "Quantum Computing",
  "Transhumanism",
  "Futurology",
  "Space Exploration",
  "Mars Colonization",
  "Space Travel",
  "Asteroid Mining",
  "Drone Technology",
  "Cybersecurity",
  "Hacking",
  "Cryptography",
  "Cyber Activism"
]


export const Shuffleinterests = (interests) => { 
  let shuffledinterests = [...interests];
  for (let i = (shuffledinterests.length - 1); i > 0 ; i--){
    const j = Math.floor(Math.random() * ( 1 + i ));
    [shuffledinterests[i], shuffledinterests[j]] = 
    [shuffledinterests[j], shuffledinterests[i]]
  }
  return shuffledinterests;
 }